spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  # 数据库驱动
    url: jdbc:mysql://localhost:3306/db_libary?useUnicode=true&characterEncoding=utf8&useSSL=false  # 数据库连接地址
    username: root  # 数据库用户名
    password: 123456  # 数据库密码

server:
  port: 9090  # 服务器端口

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 扫描mybatis xml文件路径
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名规则
